[versions]
activityCompose = "1.8.2"
agp = "8.8.2"
androidxJunit = "1.1.5"
appcompatVersion = "1.6.1"
assistantSdk = "0.1.0"
converterGson = "2.9.0"
coreKtxVersion = "1.12.0"
embeddedAssistantClient = "0.1.0"
espressoCoreVersion = "3.5.1"
generativeai = "0.9.0"
googleCloudSpeech = "2.9.0"
gson = "2.10.1"
hiltAndroid = "2.50"
hiltNavigationCompose = "1.0.0"
kotlin = "1.9.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinxCoroutinesAndroid = "1.7.3"
lifecycleViewmodelCompose = "2.8.7"
lottieCompose = "6.1.0"
material = "1.12.0"
material3Android = "1.3.1"
materialIconsExtendedVersion = "1.5.4"
navigationCompose = "2.7.6"
okhttp = "4.9.3"
porcupineAndroid = "3.0.0"
roomRuntime = "2.6.1"
roomKtx = "2.6.1"
ui = "1.6.1"
core = "1.13.0"
voskAndroid = "0.3.38"
constraintlayout = "2.1.4"
navigationFragmentKtx = "2.8.8"
navigationUiKtx = "2.8.8"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Android" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
assistant-sdk = { module = "com.google.assistant.sdk:assistant-sdk", version.ref = "assistantSdk" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
embedded-assistant-client = { module = "com.google.assistant.embedded.v1alpha2:embedded-assistant-client", version.ref = "embeddedAssistantClient" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
google-cloud-speech = { module = "com.google.cloud:google-cloud-speech", version.ref = "googleCloudSpeech" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtendedVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
porcupine-android = { module = "ai.picovoice:porcupine-android", version.ref = "porcupineAndroid" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
vosk-android = { module = "org.vosk:vosk-android", version.ref = "voskAndroid" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

